name = "hoodsly-shopify-app"
client_id = "{{ SHOPIFY_API_KEY }}"
application_url = "{{ HOST }}"
embedded = true

[access_scopes]
scopes = "write_products,read_orders,write_orders,read_customers,write_customers,read_metaobjects,write_metaobjects,read_all_orders"

[auth]
redirect_urls = [
  "{{ HOST }}/auth/callback",
  "{{ HOST }}/auth/shopify/callback",
  "{{ HOST }}/shopify/auth/callback"
]

[webhooks]
api_version = "2024-01"


[pos]
embedded = false