api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "price-calculator"
type = "function"
uid = "cced03f1-93bd-4b3c-a270-8059f4730abcc2827c85"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
